In [ ]:
#LISTAS

In [ ]:
L=["Luis",2,"Ana",[2,4,1],True,2.3,[5]]
L

['Luis', 2, 'Ana', [2, 4, 1], True, 2.3, [5]]

In [ ]:
L[2:5]

['Ana', [2, 4, 1], True]

In [ ]:
L[3][1]

4

In [ ]:
L[6][0]
L[-1][0]

5

## Listas usando funciones

In [ ]:
nota = [12,14,12,16,17,19,13,16]
nota

[12, 14, 12, 16, 17, 19, 13, 16]

In [ ]:
notaMax = max(nota)
notaMax

19

In [ ]:
notaMin = min(nota)
notaMin

12

In [ ]:
longitud = len(nota)
longitud

8

In [ ]:
OrdenAsc = sorted(nota)
OrdenAsc

[12, 12, 13, 14, 16, 16, 17, 19]

In [ ]:
OrdenDesc = sorted(nota, reverse= True)
OrdenDesc

[19, 17, 16, 16, 14, 13, 12, 12]

Aregar y remover parametros

In [ ]:
nota.append(10)
nota

[12, 14, 12, 16, 17, 19, 13, 16, 10]

In [ ]:
nota = nota + [14,16]
nota

[12, 14, 12, 16, 17, 19, 13, 16, 10, 14, 16]

In [ ]:
del(nota[0])
nota

[14, 12, 16, 17, 19, 13, 16, 10, 14, 16]

**MATRICES** :✌️

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
# Dimensión de la matriz
print(a.ndim)

1


In [ ]:
# Arreglos de 3 dimensiones
b = np.array([(2,3,2),(2,1,3),(2,0,4)])

In [ ]:
print(b)

[[2 3 2]
 [2 1 3]
 [2 0 4]]


#bucle for
####sumar los n numeros ingresados por teclado

In [ ]:
suma=0

for i in  range(5+1):
    print(i)
    suma  = suma + i
print(f"la suma es: {suma} ")

0
1
2
3
4
5
la suma es: 15 


####hallar el factorial de un numero

In [ ]:
num = int(input("Ingresa un numero: \t"))

factorial = 1

for i in range(1, num+1):
    factorial = factorial * i

print(f"El factorial de {num} es {factorial}: ")

Ingresa un numero: 	5
El factorial de 5 es 120: 


####un programa que suma los numeros ingresados por teclado

In [ ]:
n = int(input("Ingresa la cantidad de datos "))

suma = 0

while n > 0:
    dato = float(input("ingresa un dato: "))
    suma = suma + dato
    n = n-1

print(f"la suma es {suma} ")

Ingresa la cantidad de datos 3
ingresa un dato: 34
ingresa un dato: 23
ingresa un dato: 23.2
la suma es 80.2 


####implemeta un bucle infinito , cuando de ingresa el 0, calcule la suma

In [ ]:
suma = 0
while True:
    dato = float(input("ingresa el numero: "))
    if dato ==0:
        break
    suma += dato
print(f"La suma es {suma}")

ingresa el numero: 2
ingresa el numero: 3
ingresa el numero: -2
ingresa el numero: -2
ingresa el numero: 4
ingresa el numero: 0
La suma es 5.0


*FUNCIONES*

####Programa que suma dos numeros

In [ ]:
def suma(a, b):
    return a + b
suma(2,3)


5

####Programa que calcula el volumen de un cilindro

In [ ]:
import math 

def volumen_cilindro(radio, altura):
    volumen = math.pi*radio**2*altura
    return volumen
r = float(input("ingresa el radio"))
h = float(input("ingresa la altura"))

volumen = volumen_cilindro(r, h)

print(f"el volumen del cilindro es {(volumen):.2f}")



ingresa el radio4
ingresa la altura9
el volumen del cilindro es 452.39


In [ ]:
diccionario = {'nombre' : 'Carlos', 'edad' : 22, 'cursos': ['Python','Django','JavaScript'] }


{'cursos': ['Python', 'Django', 'JavaScript'], 'edad': 22, 'nombre': 'Carlos'}